### ISSUE TITLE
UnexpectedValueException

### ISSUE THREAD

**Issue by PhiloNL** [barryvdh/laravel-cors#134]
A security audit has been performed on one of our websites and a there seems to be an issue when the request headers are modified.

```
GET / HTTP/1.1
X-Forwarded-Host: 12345'"\'\");|]*%00{%0d%0a<%00>%bf%27'#??#
Referer: http://www.google.com/search?hl=en&q=testing
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.21 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.21
Client-IP: 127.0.0.1
X-Forwarded-For: 127.0.0.1
X-Forwarded-Host: 12345'"\'\");|]*%00{%0d%0a<%00>%bf%27'####
Via: 1.1 wa.www.test.com
Origin: http://www.test.com/
X-XSRF-TOKEN: eyJpdiI6Ikhia0tldVlhSGs1VXdxWkpCYUZxUHc9PSIsInZhbHVlIjoic3pxNm1kUERWeUlqTkF4ZDByakx6ZDJJbDhOUlU0b3NzeVhWdTJFVEU4TG03WXEwbFRSc2pHU3lGYzNWQTVpYk5HNHhjVU9JdFBcL29RaVRPZ3dYZG1nPT0iLCJtYWMiOiIyNTM3NTEzZmM4MDY4ZDZjZDRjNGM5OTM1MDFmNGFiYThhM2ExNGJiMDQ4YzhlOTU1MzQ5NDI3MTBmZjBmZjljIn0= (line truncated) ...5ZWxBXC95RjkzS1V0dEh4Z0VtVnExemNlZEV0UStRTkdZSXorUUtMbG02XC9lb0ZpNDZEWTVmd1krZzJCWXVrM0ZFOGhhSEtHdWtpUzVKd3JkTU1ERDNcL0dpdndKRDU3d1Arend1M3djVnpxR3RcL3NVSW1pWHdnNUNLOXBBU0doZjArdjViUGtlUlwvUGZtMjNhOEpqckJzTDBONFltTXR2K3RvNkVqYUNBVW5aaHVGNmJJVDhHQWJBN1BpQXh6eDJMXC9NdXlHYzgxVGJSWUdSc21XaUJkczBTRWdHVHQxVnAwZlU9IiwibWFjIjoiYmVjYjAxZmQzN2U3YTQ1OTZmYjQwNzk2NzY3NjMzMTMyODUyMmJiMWJmOTZkOWRmNWIyYTNlMGFjNjJhMWFlOSJ9; server=web52.c2; cookieSeen=1; 66932aa7237ce328ca0b1e9e378a38a6bee0a480=eyJpdiI6Imo1c
Cookie: server=web57.c2
Connection: close
```

The error that is thrown:

```
[2016-09-15 08:22:59] live.ERROR: exception 'UnexpectedValueException' with message 'Invalid Host "|]*%00{%0d%0a<%00>%bf%27'####"' in bootstrap/cache/compiled.php:3295
Stack trace:
#0 bootstrap/cache/compiled.php(3221): Symfony\Component\HttpFoundation\Request->getHost()
#1 bootstrap/cache/compiled.php(3234): Symfony\Component\HttpFoundation\Request->getHttpHost()
#2 vendor/barryvdh/laravel-cors/src/HandleCors.php(53): Symfony\Component\HttpFoundation\Request->getSchemeAndHttpHost()
#3 vendor/barryvdh/laravel-cors/src/HandleCors.php(33): Barryvdh\Cors\HandleCors->isSameDomain(Object(Illuminate\Http\Request))
#4 [internal function]: Barryvdh\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#5 bootstrap/cache/compiled.php(9304): call_user_func_array(Array, Array)
#6 app/Http/Middleware/Secure.php(31): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#7 [internal function]: Cms\Http\Middleware\Secure->handle(Object(Illuminate\Http\Request), Object(Closure))
#8 bootstrap/cache/compiled.php(9304): call_user_func_array(Array, Array)
#9 bootstrap/cache/compiled.php(12331): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 bootstrap/cache/compiled.php(9304): call_user_func_array(Array, Array)
#12 bootstrap/cache/compiled.php(12270): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 bootstrap/cache/compiled.php(9304): call_user_func_array(Array, Array)
#15 bootstrap/cache/compiled.php(2776): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 bootstrap/cache/compiled.php(9304): call_user_func_array(Array, Array)
#18 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 bootstrap/cache/compiled.php(9294): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 bootstrap/cache/compiled.php(2053): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 bootstrap/cache/compiled.php(2036): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#22 public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#23 {main}  
```

**Comment by barryvdh** [comment]
Closing this as part of an issue-cleanup. Please re-open if this is still an issue on the latest version.
